### ISSUE TITLE
Migration saves violate not-null constraint error

### ISSUE THREAD

**Issue by Dostonbek1** [ansible/django-ansible-base#128]
### Bug Summary

While trying to use the RBAC library, I hit the following error when I try to create an organization object

```
django.db.utils.IntegrityError: null value in column "created_on" of relation "core_organization" violates not-null constraint
DETAIL:  Failing row contains (1, null, null, Default Org, A default placeholder organization, null, null).
```

`created_on` and `modified_on` fields should have the following args added, `auto_add_now=True` and `auto_now=True` respectively.

**Comment by AlanCoding** [comment]
Specifically, this is hit trying to create an Organization, from AbstractOrganization, in migration RunPython code.

**Comment by AlanCoding** [comment]
Believed to be fixed in https://github.com/ansible/django-ansible-base/pull/209 by @john-westcott-iv

**Comment by Dostonbek1** [comment]
Confirmed that this issue is resolved with the PR linked above.
