### ISSUE TITLE
Convert to CommandError

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/django-ansible-base#211]
### Bug Summary

In ansible_base/authentication/management/commands/authenticators.py we call system.exit if there is no admin user defined. Instead we should raise a CommandError and let django deal with it accordingly. See comments in https://github.com/ansible/django-ansible-base/pull/209.

**Comment by Kuppjaerk** [comment]
Hi, I just submitted a PR for this issue. Please let me know if anything else needs to be done apart from this simple fix!
