### ISSUE TITLE
[activity stream] Be able to filter JSONField contents

### ISSUE THREAD

**Issue by relrod** [ansible/django-ansible-base#277]
Right now, filtering doesn't seem to work for `JSONField`:

If I go to this URL in test_app: http://localhost:8000/api/v1/activitystream/?changes__added_fields__id__exact=2

I get a 400 with:

``` json
{
    "detail": "No related model for field added_fields."
}

```

This comes from our `rest_filters` source. It seems we assume that double-underscore means related model, but for `JSONField`, it doesn't mean that.

This makes it hard to do cool filtering on activity stream entries.

**Comment by relrod** [comment]
Maybe @AlanCoding has some thoughts here, since most of our current filtering code came out of AWX.

**Comment by AlanCoding** [comment]
I don't think this was possible in AWX. You could write a special case for this. The JSONFields in AWX were not real JSONFields @jbradberry can probably elaborate more.

**Comment by relrod** [comment]
I played around a bit today with our `rest_filters` logic and I can get JSONField "working", but the issue ends up coming down to value types.

JSONFields are schemaless. The value for the filter always comes in as a string from the querystring.

So for `?changes__added_fields__id__exact=2` we end up generating `Q(changes__added_fields__id__exact="2")`

Making 2 an int there makes that a very valid query. But we have no way of knowing if it really should be an int or a string or what...

So,  with my playing around, I have it working for **string** values. You can do `?changes__added_fields__email__iexact=admin@stuff.invalid` and get what you expect. But it doesn't work for `id` or any other non-string values.

I'm not sure what the answer is here. Any solution I can think of is going to get much more complex than I'm comfortable with maintaining. But without a solution, you can't really expose a truly searchable interface to Activity Stream which is a little unfortunate.

**Comment by relrod** [comment]
~We could do something custom for Activity Stream... We *know* the model the `changes` blob relates to. We can do "stuff" to see what the model expects each field to be, and try to cast (there's already machinery for that, `value_to_python_for_field`).~

~That's a very "Activity Stream-only" solution, but it could work - DRF lets us set the filter backend at the view(set) level.~

After more thought, I don't think this works at all. We *don't* know the model. I mean, we store that, but you'd have to load that in from every `Entry` and then for each `Entry`, resolve that from a content_type id into its class name and filter based on each field. That's going to be *extremely* slow.

I don't know of a good way to do this.

**Comment by AlanCoding** [comment]
This works

http://127.0.0.1:8000/api/v1/activitystream/?changes__icontains=dog

I don't think this is any less functional than its predecessor in AWX, and I would prefer to delay digging deep into a solution that might have other drawbacks.

**Comment by relrod** [comment]
But that's only doing a text search of the JSONField.

In AWX, you can do stuff like:

/api/v2/activity_stream/?job__id__gt=4900

because each activity stream entry stores a reference to every possible model that can have activity stream entries for it.

There's no analog to this right now in the DAB activity stream.

**Comment by AlanCoding** [comment]
/api/v2/activity_stream/?job__id__gt=4900 --> http://127.0.0.1:8000/api/v1/activitystream/?object_id=1&content_type__model=animal

The `__gt` isn't practically useful. The `__in` still works, which clients would actually use.

I still say we're good with this. At least near-term. Again, per https://github.com/ansible/django-ansible-base/issues/251, users won't be able to come up with this on their own, and some related links will do the trick.

**Comment by relrod** [comment]
Okay for the particular case of the object's id, yes there's a way to filter it. But more generally it's impossible to do "deep" filtering of the stored changes, and that's my concern.

I'm worried that if we don't address this now, we're locking ourselves in to never being able to query activity stream properly. This doesn't seem like something that's going to be easy to fix later. If we don't address this now, we're effectively limiting ourselves to only being able to substring-search the changes rather than structurally search them and I think that's giving up a lot of flexibility in the future.
