### ISSUE TITLE
Two remaining contractual issues for association endpoints

### ISSUE THREAD

**Issue by AlanCoding** [ansible/django-ansible-base#393]
This is assuming https://github.com/ansible/django-ansible-base/pull/370 is merged. This issue outlines two things that I discovered probably should be changed while doing that, but seemed to disruptive to do at that time. This issue should be a discussion.

### Respecting original viewset `get_queryset`

You can see in the logic of that PR, this code blurb is moved, but not changed.

```python
        if self.queryset:
            qs = self.queryset
            cls = self.queryset.model
        else:
            cls = self.serializer_class.Meta.model
            qs = cls.objects.all()
```

This is used to produce the queryset, which is used to produce the serializer, which is used to associate and disassociate instances. Since this is for using in the `PrimaryKeyRelatedField`, it generally _feels_ like it makes sense to use the "full" queryset of the model. Otherwise though, generally, if `self.queryset` is not set, you wouldn't go to `cls.objects.all()` if you have the view (we do). You would generally go to `self.get_queryset()`.

Previously this might have been blocked because we declared DAB standard practice to give the visible queryset to the requesting user in `get_queryset`, but this is no longer the case. Now, `filter_queryset` will filter down to what the user can see, and `get_queryset` should contain all objects, minus any business logic specific to that view. Like, let's say you had endpoints to show objects with the `active` field set to `True` and another endpoint to show objects with `active` set to `False`. You should do this in `get_queryset`. But the association endpoints won't carry this through unless you set a static `.queryset`, which isn't always possible.

So I'm arguing the `else:` here should defer to the view's `get_queryset`.

### Disassociation queryset

We are still maintaining this stuff

```python
        # Ensure each of the given related_instances is actually related to the instance.
        # If any isn't, then bomb out and tell the user which ones aren't related.
        given_related_instance_set = set(related_instances)
        related_instance_set = set(manager.all())
        non_related_instances = given_related_instance_set - related_instance_set
        if non_related_instances:
            raise serializers.ValidationError(
                {
                    'instances': _('Cannot disassociate these objects because they are not all related to this object: %(non_related_instances)s')
                    % {'non_related_instances': ', '.join(str(i.pk) for i in non_related_instances)},
                }
            )
```

This is inefficient, and I don't think we should do it.

Alternatively, I think the queryset for `instances` of the _disassociation_ serializer should effectively defer to `getattr(parent_instance, self.association_fk).all()`. In other words, only already-associated objects are taken to be valid choices. That way, the queryset for the `instances` field does this work for us and we don't need this logic at all.

In the new code, this would mean deferring to `get_sublist_queryset`... but I would like that to be customizable, so really introduce a new method like `get_associated_objects_qs`, and have `get_sublist_queryset` _call that_, in case someone wanted to customize the sublist queryset with additional filtering. Such filtering should not be applied to dissociation actions.

There is only 1 wrinkle in this, which is that an object which is not currently association would return a "does not exist" error. I suggest that we should fix this in the error message. So for `instances` in the disassociation serializer, you would not get "does not exist" errors, but instead a hybrid "does not exist or is not a related item" message. This is not a security problem, because permission to modify the parent object should have already been checked by this point in code.

**Comment by relrod** [comment]
I think these both make sense to fix. It would be really nice to get rid of the manual checking on disassociation and I think what you propose is a clean way to do that.

And your example for how we can get inconsistent querysets if a viewset overrides `get_queryset()` or `filter_queryset()` but doesn't set `.queryset` to match is convincing.

I'm +1 on fixing both of these.

**Comment by AlanCoding** [comment]
merged.
