### ISSUE TITLE
CI test "test_radius.py::test_authenticator_plugin" fails randomly

### ISSUE THREAD

**Issue by BrennanPaciorek** [ansible/django-ansible-base#428]
### Bug Summary

Across multiple commits and PRs, `test_radius.py::test_authenticator_plugin` appears to fail randomly in the same way:
```python
backend_cls = <MagicMock name='RADIUSBackend' id='140395987507952'>
unauthenticated_api_client = <rest_framework.test.APIClient object at 0x7fb07cf5a8e0>
radius_configuration = {'PORT': 1812, 'SECRET': 'testingsecret', 'SERVER': 'localhost'}
radius_authenticator = <Authenticator: Test RADIUS Authenticator>
user = <User: user>

    @mock.patch("rest_framework.views.APIView.authentication_classes", [SessionAuthentication])
    @mock.patch("ansible_base.authentication.authenticator_plugins.radius.RADIUSBackend")
    def test_authenticator_plugin(backend_cls, unauthenticated_api_client, radius_configuration, radius_authenticator, user):
        """
        Test RADIUS authenticator logic.
    
        Test that the RADIUS backend is created with the correct settings.
        Test that login credentials are passed to the backend's authenticate() method call.
        Test that associated AuthenticatorUser record is created.
        """
        backend = backend_cls.return_value
        backend.authenticate.return_value = RADIUSUser(
            username="user",
            groups=["users", "managers"],
            is_staff=False,
            is_superuser=False,
        )
    
        client = unauthenticated_api_client
        client.login(username="user", ***)
    
        url = reverse(authenticated_test_page)
        response = client.get(url)
        assert response.status_code == 200
    
>       backend_settings = backend_cls.call_args[0][0]
E       TypeError: 'NoneType' object is not subscriptable

test_app/tests/authentication/authenticator_plugins/test_radius.py:77: TypeError
```

This case fails in devel commit https://github.com/ansible/django-ansible-base/commit/0b4d0138f3572829ba6e21efbf16758dadba26fb and the PR to revert this commit: #426
Since applying and undoing this patch both produce this error, I do not think the commit is the root cause.

Bug Reproduction: I cannot reproduce this locally. I have attempted restricting local pytest worker counts to 4 (the amount used by GitHub actions job)
I have not tried testing running pytest in a virtualized Ubuntu instance.

Expected Resolution: One of the below
- Figure out the trigger for this failure, and fix the root cause (ideal)
- Refactor the test case `test_radius.py::test_authenticator_plugin` to be more resilient to the random failure (not as good)
-  xfail `test_radius.py::test_authenticator_plugin` (not good solution)

**Comment by BrennanPaciorek** [comment]
I will be working on this myself, and only opened this issue in the event anyone has any ideas for identifying the root cause of this.

**Comment by AlanCoding** [comment]
I saw this in the checks for a docs PR https://github.com/ansible/django-ansible-base/pull/425, ping @john-westcott-iv , because her was working on this in some respect.

What doesn't make any sense to me is how this could be flaky, since the None is coming from the mock argument. That doesn't make any sense to me. It should be deterministic.
