### ISSUE TITLE
Add a setting that treats `object_id` in DAB RBAC as an integer

### ISSUE THREAD

**Issue by AlanCoding** [ansible/django-ansible-base#450]
Proposal:

Introduce a new setting in the DAB RBAC section that specifies:

> Treat the `object_id` field (local ids for references) as an integer field in the API

Internally, we may continue to use a string type indefinitely for consistency with resource registry and to support uuids. However, many apps have no need to support uuid primary keys. For those, it may cause fewer problems for clients to have the `object_id`, as presented in the API, to be an integer.

This is fairly straightforward to implement. Although serializers may derive type from the model, this is trivial to override to a nullable integer field in the serializer. I don't desire that test_app use this setting by default, but we should have tests for this.

It is unclear if we should have something similar for resource registry.

**Comment by rh-carogers** [comment]
After review, I am closing this issue as Won't Do. Unless we can guarantee that all foreign keys can be interpreted as an int, we should keep the current implementation.
