### ISSUE TITLE
Have a sane default for `RESOURCE_SERVICE_PATH`

### ISSUE THREAD

**Issue by AlanCoding** [ansible/django-ansible-base#595]
We have many values floating around for the default value of this settings, and sometimes in non-setting form, like this:

https://github.com/ansible/django-ansible-base/blob/21c652631641e3adf5b9cdbb43bb79cbb04fb1ac/ansible_base/resource_registry/tasks/sync.py#L68

^ that value above is what I would like to be the default. I do not want this to be another thing the installer has to set.

And the silent no-op here makes it very difficult to debug anything, and the path to enabling this very challenging.

https://github.com/ansible/django-ansible-base/blob/21c652631641e3adf5b9cdbb43bb79cbb04fb1ac/ansible_base/resource_registry/apps.py#L104-L107

**Comment by relrod** [comment]
This is fixed by #582...

**Comment by relrod** [comment]
https://github.com/ansible/django-ansible-base/pull/597
